package com.yalantis.ucrop.uicontroller;

import android.content.Context;
import android.content.Intent;
import android.support.v7.widget.GridLayoutManager;
import android.view.View;
import android.view.ViewGroup;

import com.bumptech.glide.Glide;
import com.yalantis.ucrop.model.M_Img;
import com.yalantis.ucrop.util.StartGalleryAndCamera;

import java.io.File;
import java.util.ArrayList;

/**
 * Generated by Android Module Generator By:DecentAnt V2.8
 * Company： www.chisalsoft.com
 * Time： 2018-02-02 11:51:35
 * Usage：
 */
public class Activity_Main extends AppBaseCompatActivity<View_Main> {

	private UcropRecyclerAdapter<Item_Img, M_Img> ucropRecyclerAdapter;

	@Override
	protected View_Main initViewObject(Context context) {
		return new View_Main(context);
	}

	private final String TAG = Activity_Main.class.getName();
	private ArrayList<M_Img> dataList;
	private StartGalleryAndCamera startGalleryAndCamera;
	private Activity_Main activity_main = this;
	private Context context = this;

	@Override
	protected void initVariable() {
		dataList = new ArrayList<>();
		startGalleryAndCamera = new StartGalleryAndCamera(this, this, dataList);
		startGalleryAndCamera.setMaxImgs(1);
		startGalleryAndCamera.setFlashMode(StartGalleryAndCamera.FLASH_MODE_ON);
		startGalleryAndCamera.setImgMaxSize(256*1024);
		startGalleryAndCamera.setNeedCrop(true);
		startGalleryAndCamera.setNeedPreview(true);
		initRv();
	}

	private void initRv() {
		ucropRecyclerAdapter = new UcropRecyclerAdapter<Item_Img, M_Img>(context, dataList) {
			@Override
			public Item_Img setViewHolder(ViewGroup parent) {
				return new Item_Img(context, parent);
			}

			@Override
			public void setData(Item_Img v, final int position, M_Img m) {
				Glide.with(context).load(new File(m.getPath())).skipMemoryCache(false).into(v.getImageView_pic());
				v.getTextView_info().setText("位置：" + position + "\n文件名：" + m.getImgName() + "\n路径：" + m.getPath() + "\n所属文件夹：" + m.getDirName() + "\n图片ID：" + m.getId() + "\n文件夹ID：" + m.getDirID());
				v.getRootView().setOnClickListener(new View.OnClickListener() {
					@Override
					public void onClick(View v) {
						startGalleryAndCamera.startPreview(position);
					}
				});
			}
		};
		getViewObject().getRecyclerView_imgRv().setAdapter(ucropRecyclerAdapter);
		GridLayoutManager gridLayoutManager = new GridLayoutManager(context, 2);
		getViewObject().getRecyclerView_imgRv().setLayoutManager(gridLayoutManager);
	}

	@Override
	protected void setListener() {
		getViewObject().getButton_selectGalleryBtn().setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				startGalleryAndCamera.startGallery();
			}
		});

		getViewObject().getButton_selectCameraBtn().setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				startGalleryAndCamera.startCamera();
			}
		});

	}

	@Override
	protected void onActivityResult(int requestCode, int resultCode, final Intent data) {
		super.onActivityResult(requestCode, resultCode, data);
		startGalleryAndCamera.onActivityResult(requestCode, resultCode, data, ucropRecyclerAdapter);
	}
}