package com.yalantis.ucrop.uicontroller;

import android.content.Context;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.LinearLayout;

import com.yalantis.ucrop.R;


/**
 * Generated by Android Module Generator By:DecentAnt V2.8
 * Company： www.chisalsoft.com
 * Time： 2018-02-08 13:45:42
 * Usage：
 */
public class Item_WholePic extends BaseItem {
	private final String TAG = Item_WholePic.class.getName();
	protected ImageView imageView_showPic;
	protected LinearLayout linearLayout_wholeItem;

	public Item_WholePic(Context context, ViewGroup parent) {
		super(context, parent, R.layout.item_whole_pic);
		initView(rootView);
	}

	private void initView(View rootView) {
		imageView_showPic = (ImageView) rootView.findViewById(R.id.showPic);
		linearLayout_wholeItem = (LinearLayout) rootView.findViewById(R.id.wholeItem);
	}

	public ImageView getImageView_showPic() {
		return imageView_showPic;
	}

	public LinearLayout getLinearLayout_wholeItem() {
		return linearLayout_wholeItem;
	}
}
