package com.yalantis.ucrop.uicontroller;

import android.content.Context;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import com.yalantis.ucrop.R;


/**
 * Generated by Android Module Generator By:DecentAnt V2.8
 * Company： www.chisalsoft.com
 * Time： 2018-02-02 11:55:27
 * Usage：
 */
public class Item_Img extends BaseItem {
	private final String TAG = Item_Img.class.getName();
	protected ImageView imageView_pic;
	protected TextView textView_info;

	public Item_Img(Context context, ViewGroup parent) {
		super(context, parent, R.layout.item_img);
		initView(rootView);
	}

	private void initView(View rootView) {
		imageView_pic = (ImageView) rootView.findViewById(R.id.pic);
		textView_info = (TextView) rootView.findViewById(R.id.info);
	}

	public ImageView getImageView_pic() {
		return imageView_pic;
	}

	public TextView getTextView_info() {
		return textView_info;
	}

}
