package com.yalantis.ucrop.uicontroller;


import android.content.Context;
import android.view.SurfaceView;
import android.view.View;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;

import com.yalantis.ucrop.R;


/**
 * Generated by Android Module Generator By:DecentAnt V2.8
 * Company： www.chisalsoft.com
 * Time： 2018-01-09 15:09:44
 * Usage：
 */
public class View_DctCamera extends ViewObject {
	protected SurfaceView surfaceView_cameraPreview;
	protected ImageView imageView_cancel;
	protected ImageView imageView_reverse;
	protected LinearLayout linearLayout_buttonPanelLl;
	protected LinearLayout linearLayout_isFailLl;
	protected TextView textView_failInfoTv;
	protected ImageView imageView_openCamera;
	protected ImageView imageView_flashMode;

	public View_DctCamera(Context context) {
		super(context, R.layout.activity_dct_camera);
		initView(rootView);
	}

	private void initView(View rootView) {
		surfaceView_cameraPreview = (SurfaceView) rootView.findViewById(R.id.cameraPreview);
		imageView_cancel = (ImageView) rootView.findViewById(R.id.cancel);
		imageView_reverse = (ImageView) rootView.findViewById(R.id.reverse);
		linearLayout_buttonPanelLl = (LinearLayout) rootView.findViewById(R.id.buttonPanelLl);
		linearLayout_isFailLl = (LinearLayout) rootView.findViewById(R.id.isFailLl);
		textView_failInfoTv = (TextView) rootView.findViewById(R.id.failInfoTv);
		imageView_openCamera = (ImageView) rootView.findViewById(R.id.openCamera);
		imageView_flashMode = (ImageView) rootView.findViewById(R.id.flashMode);
	}

	public SurfaceView getSurfaceView_cameraPreview() {
		return surfaceView_cameraPreview;
	}

	public ImageView getImageView_cancel() {
		return imageView_cancel;
	}

	public ImageView getImageView_reverse() {
		return imageView_reverse;
	}

	public LinearLayout getLinearLayout_buttonPanelLl() {
		return linearLayout_buttonPanelLl;
	}

	public LinearLayout getLinearLayout_isFailLl() {
		return linearLayout_isFailLl;
	}

	public TextView getTextView_failInfoTv() {
		return textView_failInfoTv;
	}

	public ImageView getImageView_openCamera() {
		return imageView_openCamera;
	}

	public ImageView getImageView_flashMode() {
		return imageView_flashMode;
	}
}