package com.yalantis.ucrop.uicontroller;

import android.content.Context;
import android.support.v7.widget.RecyclerView;
import android.view.View;
import android.widget.Button;

import com.yalantis.ucrop.R;


/**
 * Generated by Android Module Generator By:DecentAnt V2.8
 * Company： www.chisalsoft.com
 * Time： 2018-02-02 17:55:25
 * Usage：
 */
public class View_Main extends ViewObject {
	protected Button button_selectGalleryBtn;
	protected Button button_selectCameraBtn;
	protected RecyclerView recyclerView_imgRv;

	public View_Main(Context context) {
		super(context, R.layout.activity_main);
		initView(rootView);
	}

	private void initView(View rootView) {
		button_selectGalleryBtn = (Button) rootView.findViewById(R.id.selectGalleryBtn);
		button_selectCameraBtn = (Button) rootView.findViewById(R.id.selectCameraBtn);
		recyclerView_imgRv = (RecyclerView) rootView.findViewById(R.id.imgRv);
	}

	public Button getButton_selectGalleryBtn() {
		return button_selectGalleryBtn;
	}

	public Button getButton_selectCameraBtn() {
		return button_selectCameraBtn;
	}

	public RecyclerView getRecyclerView_imgRv() {
		return recyclerView_imgRv;
	}

}